version: 2.1

executors:
  conda-executor:
    docker:
      - image: continuumio/miniconda3
    working_directory: ~/project

jobs:
  setup-conda:
    executor: conda-executor
    steps:
      - checkout
      - run:
          name: Create Conda environment
          command: |
            conda env create -f envs/environment.yml
            conda init bash
      - run:
          name: Activate environment
          command: |
            source ~/.bashrc
            conda activate credit-alpha-rl

  run-tests:
    executor: conda-executor
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
            source ~/.bashrc
            conda activate credit-alpha-rl
            pytest --maxfail=1 --disable-warnings -q

  lint:
    executor: conda-executor
    steps:
      - checkout
      - run:
          name: Lint code
          command: |
            source ~/.bashrc
            conda activate credit-alpha-rl
            flake8 agents envs backtests dashboards utils

workflows:
  version: 2
  ci-pipeline:
    jobs:
      - setup-conda
      - run-tests:
          requires:
            - setup-conda
      - lint:
          requires:
            - setup-conda
